name: invoiceninja
version: '1.0.7'
summary: Online Invoicing
description: Create invoices, accept payments, track expenses & time-tasks
confinement: strict
base: core18
grade: stable

apps:
  invoiceninja-flutter:
    command: Invoice_Ninja
    extensions: [flutter-master]

parts:
  invoiceninja-flutter:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart