name: invoiceninja
version: '1.0.9'
summary: Online Invoicing
description: Create invoices, accept payments, track expenses & time-tasks
confinement: strict
base: core18
grade: stable

apps:
  invoiceninja:
    command: invoiceninja
    extensions: [flutter-master]

parts:
  invoiceninja:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart